export default {
	3dmodel: require('./3dmodel.png'),
	about.1: require('./about.1.jpeg'),
	address: require('./address.png'),
	app: require('./app.png'),
	bg_1: require('./bg_1.jpg'),
	blender: require('./blender.png'),
	c_sharp: require('./c-sharp.png'),
	css: require('./css.png'),
	desktop: require('./desktop.png'),
	email: require('./email.png'),
	flutter: require('./flutter.png'),
	graphic: require('./graphic.png'),
	html: require('./html.png'),
	java: require('./java.png'),
	javascript: require('./javascript.png'),
	loc: require('./loc.png'),
	partner_1: require('./partner-1.png'),
	partner_2: require('./partner-2.png'),
	partner_3: require('./partner-3.png'),
	partner_4: require('./partner-4.png'),
	partner_5: require('./partner-5.png'),
	phone: require('./phone.png'),
	photoshop: require('./photoshop.png'),
	python: require('./python.png'),
	uiux: require('./uiux.png'),
	web: require('./web.png'),
};